[package]
name = "arccluster-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.5", features = ["web"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-sys = { version = "0.1" }
wasm-bindgen-futures = "0.4"
